-- MySQL Script generated by MySQL Workbench
-- sáb 01 out 2022 01:57:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(120) NOT NULL,
  `CEP` VARCHAR(45) NOT NULL,
  `Endereco` VARCHAR(255) NOT NULL,
  `Contato` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa_Fisica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pessoa_Fisica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa_Fisica` (
  `idPessoa_Fisica` INT NOT NULL AUTO_INCREMENT,
  `CPF` VARCHAR(14) NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idPessoa_Fisica`),
  INDEX `fk_Pessoa_Fisica_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa_Fisica_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa_Juridica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pessoa_Juridica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa_Juridica` (
  `idPessoa_Fisica` INT NOT NULL AUTO_INCREMENT,
  `CNPJ` VARCHAR(18) NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idPessoa_Fisica`),
  INDEX `fk_Pessoa_Juridica_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa_Juridica_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Veiculo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Veiculo` (
  `idVeiculo` INT NOT NULL AUTO_INCREMENT,
  `Fabricante` VARCHAR(45) NOT NULL,
  `Modelo` VARCHAR(45) NOT NULL,
  `Ano` INT NOT NULL,
  `Placa` VARCHAR(8) NOT NULL,
  `Chassi` VARCHAR(45) NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idVeiculo`, `Cliente_idCliente`),
  INDEX `fk_Veiculo_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Veiculo_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`OS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`OS` (
  `idOS` INT NOT NULL AUTO_INCREMENT,
  `Identificador` VARCHAR(14) GENERATED ALWAYS AS (),
  `Data_Emissao` DATE NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Data_Conclusao` DATE NOT NULL,
  `Veiculo_idVeiculo` INT NOT NULL,
  `Veiculo_Cliente_idCliente` INT NOT NULL,
  `Valor_Total` FLOAT NOT NULL,
  `Aprovado` TINYINT NOT NULL,
  PRIMARY KEY (`idOS`, `Veiculo_idVeiculo`, `Veiculo_Cliente_idCliente`),
  INDEX `fk_OS_Veiculo1_idx` (`Veiculo_idVeiculo` ASC, `Veiculo_Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_OS_Veiculo1`
    FOREIGN KEY (`Veiculo_idVeiculo` , `Veiculo_Cliente_idCliente`)
    REFERENCES `mydb`.`Veiculo` (`idVeiculo` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Servicos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Servicos` (
  `idServicos` INT NOT NULL AUTO_INCREMENT,
  `Tipo_Mao_De_Obra` VARCHAR(90) NOT NULL,
  `Valor_Mao_De_Obra` FLOAT NOT NULL,
  PRIMARY KEY (`idServicos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pecas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pecas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pecas` (
  `idPecas` INT NOT NULL AUTO_INCREMENT,
  `Tipo_Peca` VARCHAR(45) NOT NULL,
  `Valor_Peca` FLOAT NOT NULL,
  PRIMARY KEY (`idPecas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente_Pede_OS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente_Pede_OS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente_Pede_OS` (
  `Cliente_idCliente` INT NOT NULL,
  `OS_idOS` INT NOT NULL,
  `Tipo_OS` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Cliente_idCliente`, `OS_idOS`),
  INDEX `fk_Cliente_has_OS_OS1_idx` (`OS_idOS` ASC) VISIBLE,
  INDEX `fk_Cliente_has_OS_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_has_OS_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_OS_OS1`
    FOREIGN KEY (`OS_idOS`)
    REFERENCES `mydb`.`OS` (`idOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mecanico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mecanico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mecanico` (
  `idMecanicos` INT NOT NULL AUTO_INCREMENT,
  `Matricula` VARCHAR(14) GENERATED ALWAYS AS (),
  `Nome` VARCHAR(120) NOT NULL,
  `Endereco` VARCHAR(255) NOT NULL,
  `Contato` VARCHAR(11) NOT NULL,
  `Especialidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMecanicos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mecanico_Preenche_OS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mecanico_Preenche_OS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mecanico_Preenche_OS` (
  `OS_idOS` INT NOT NULL,
  `Mecanico_idMecanico` INT NOT NULL,
  PRIMARY KEY (`OS_idOS`, `Mecanico_idMecanico`),
  INDEX `fk_OS_has_Mecanicos_Mecanicos1_idx` (`Mecanico_idMecanico` ASC) VISIBLE,
  INDEX `fk_OS_has_Mecanicos_OS1_idx` (`OS_idOS` ASC) VISIBLE,
  CONSTRAINT `fk_OS_has_Mecanicos_OS1`
    FOREIGN KEY (`OS_idOS`)
    REFERENCES `mydb`.`OS` (`idOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OS_has_Mecanicos_Mecanicos1`
    FOREIGN KEY (`Mecanico_idMecanico`)
    REFERENCES `mydb`.`Mecanico` (`idMecanicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OS_has_Pecas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`OS_has_Pecas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`OS_has_Pecas` (
  `OS_idOS` INT NOT NULL,
  `Pecas_idPecas` INT NOT NULL,
  PRIMARY KEY (`OS_idOS`, `Pecas_idPecas`),
  INDEX `fk_OS_has_Pecas_Pecas1_idx` (`Pecas_idPecas` ASC) VISIBLE,
  INDEX `fk_OS_has_Pecas_OS1_idx` (`OS_idOS` ASC) VISIBLE,
  CONSTRAINT `fk_OS_has_Pecas_OS1`
    FOREIGN KEY (`OS_idOS`)
    REFERENCES `mydb`.`OS` (`idOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OS_has_Pecas_Pecas1`
    FOREIGN KEY (`Pecas_idPecas`)
    REFERENCES `mydb`.`Pecas` (`idPecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OS_has_Servicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`OS_has_Servicos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`OS_has_Servicos` (
  `OS_idOS` INT NOT NULL,
  `Servicos_idServicos` INT NOT NULL,
  PRIMARY KEY (`OS_idOS`, `Servicos_idServicos`),
  INDEX `fk_OS_has_Servicos_Servicos1_idx` (`Servicos_idServicos` ASC) VISIBLE,
  INDEX `fk_OS_has_Servicos_OS1_idx` (`OS_idOS` ASC) VISIBLE,
  CONSTRAINT `fk_OS_has_Servicos_OS1`
    FOREIGN KEY (`OS_idOS`)
    REFERENCES `mydb`.`OS` (`idOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OS_has_Servicos_Servicos1`
    FOREIGN KEY (`Servicos_idServicos`)
    REFERENCES `mydb`.`Servicos` (`idServicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
